In [7]:
#  numpy类库的使用
import numpy as np

In [16]:
bb = np.eye(5)
bb

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
print(type([1,2,3]))
print(type(np.eye(4)))

<class 'list'>
<class 'numpy.ndarray'>


In [10]:
# 这就是创建了一个ndarray对象
type(np.array([1,23,4]))

numpy.ndarray

In [17]:
a = np.array([1,2,3,4,5], ndmin =  1)
print(a)

[1 2 3 4 5]


In [12]:
dt = np.dtype(np.float)
print(dt)

float64


In [13]:
aa = np.array([1.444, 22 ,3,4],dtype = np.float)
print(aa)
print(len(aa))

[ 1.444 22.     3.     4.   ]
4


In [22]:
aa.reshape(-1,4) # reshape 成 第一维随意，第二维满足4个元素


aa = aa.reshape(2,2)

In [59]:
np.arange(1,10,2) # 从1到10 生成1，1+2，3+2,... 步长是2

array([1, 3, 5, 7, 9])

In [80]:
a1 = np.linspace(0,100,21) # 均匀分成20段，一共21个数字
a1.shape

(21,)

In [82]:
a1.reshape(-1,21)

array([[  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
         55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.]])

In [89]:
a = np.arange(10)
s = slice(2,7,2)   # 从索引 2 开始到索引 7 停止，间隔为2
print(a)
print(s)
print (a[s])
print(a[2:-1]) # 包括开始索引，不包括终止索引8

[0 1 2 3 4 5 6 7 8 9]
slice(2, 7, 2)
[2 4 6]
[2 3 4 5 6 7 8]


In [95]:
# 二维切片
a2 = np.arange(20).reshape(4,5)
print(a2)
a2[0:2,1:4]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([[1, 2, 3],
       [6, 7, 8]])

In [100]:
ar1 = np.arange(20).reshape(4,5)
ar2 = np.arange(5)
print(ar1)
print(ar2)
print(ar1 + ar2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[0 1 2 3 4]
[[ 0  2  4  6  8]
 [ 5  7  9 11 13]
 [10 12 14 16 18]
 [15 17 19 21 23]]


In [107]:
ar2.reshape(-1,1).T

array([[0, 1, 2, 3, 4]])

In [110]:
# 连接数组
a = np.array([[1,2],[3,4]])
 
print ('第一个数组：')
print (a)
print ('\n')
b = np.array([[5,6],[7,8]])
 
print ('第二个数组：')
print (b)
print ('\n')
# 两个数组的维度相同
 
print ('沿轴 0 连接两个数组：')
print (np.concatenate((a,b)))
print ('\n')
 
print ('沿轴 1 连接两个数组：')
print (np.concatenate((a,b),axis = 1))

第一个数组：
[[1 2]
 [3 4]]


第二个数组：
[[5 6]
 [7 8]]


沿轴 0 连接两个数组：
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


沿轴 1 连接两个数组：
[[1 2 5 6]
 [3 4 7 8]]


In [133]:
ar3 = np.arange(20).reshape(4,5)
print(ar3,"\n")
ar4 = np.arange(10).reshape(-1,5)
ar5 = np.arange(10,30).reshape(-1,5)
print(ar4,"\n")
print(ar5,"\n")
print(np.concatenate((ar3,ar4)),"\n")
print((ar3,ar4))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [ 0  1  2  3  4]
 [ 5  6  7  8  9]] 

(array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]]), array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]]))


In [145]:
print(np.stack((ar3,ar5),axis=1))

bb = np.stack((ar3,ar5))
bb.shape

[[[ 0  1  2  3  4]
  [10 11 12 13 14]]

 [[ 5  6  7  8  9]
  [15 16 17 18 19]]

 [[10 11 12 13 14]
  [20 21 22 23 24]]

 [[15 16 17 18 19]
  [25 26 27 28 29]]]


(2, 4, 5)

In [131]:
print(np.vstack((ar3,ar5)))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [141]:
# 高斯分布
np.random.normal(size=(3,4))

array([[-1.02250989,  0.60445657,  0.15755827,  0.22473713],
       [-0.93956511,  0.84094584, -0.63469963, -0.10640138],
       [ 0.67509852, -0.0994849 ,  0.81351751, -0.45205141]])

In [140]:
np.random.rand(3,4)

array([[0.68337641, 0.70225787, 0.29622243, 0.81214941],
       [0.4354999 , 0.98733563, 0.6038437 , 0.98037093],
       [0.9368218 , 0.30468821, 0.87493858, 0.71000341]])